### ISSUE TITLE
Non Prime members presented with intermediate page during checkout

### ISSUE THREAD

**Issue by shanewiseman** [Hari-Nagarajan/fairgame#150]
After adding item to cart and attempting to "proceed to checkout" (sc-buy-box-ptc-button), non prime members are presented with an intermediate page before arriving at pyo page.

![image](https://user-images.githubusercontent.com/8761990/94330887-3524c180-ff96-11ea-991a-1e794272c195.png)

**Comment by shanewiseman** [comment]
```
(nvidia-bot2) bash-3.2$ python app.py amazon --test
INFO: "2020-09-26 11:34:29,595 - Initializing notification handlers
INFO: "2020-09-26 11:34:29,596 - Enabled Handlers: ['Audio']
{'BASE_URL': 'https://www.amazon.com/', 'CART_URL': 'https://www.amazon.com/gp/aws/cart/add.html'}
INFO: "2020-09-26 11:34:33,579 - Already logged in
INFO: "2020-09-26 11:34:33,580 - Checking stock for items.
INFO: "2020-09-26 11:34:34,042 - One or more items in stock!
INFO: "2020-09-26 11:34:40,026 - Clicking continue.
INFO: "2020-09-26 11:34:43,952 - Waiting for Cart Page
INFO: "2020-09-26 11:34:43,959 - On cart page.
INFO: "2020-09-26 11:34:43,960 - clicking checkout.
INFO: "2020-09-26 11:34:44,581 - Waiting for Place Your Order Page
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "/Users/sw1043146/.local/share/virtualenvs/nvidia-bot2-ZF3XGFqN/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sw1043146/.local/share/virtualenvs/nvidia-bot2-ZF3XGFqN/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/sw1043146/.local/share/virtualenvs/nvidia-bot2-ZF3XGFqN/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sw1043146/.local/share/virtualenvs/nvidia-bot2-ZF3XGFqN/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sw1043146/.local/share/virtualenvs/nvidia-bot2-ZF3XGFqN/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sw1043146/nvidia-bot2/cli/cli.py", line 44, in amazon
    amzn_obj.run_item(test=test)
  File "/Users/sw1043146/nvidia-bot2/stores/amazon.py", line 122, in run_item
    self.checkout(test=test)
  File "/Users/sw1043146/nvidia-bot2/stores/amazon.py", line 207, in checkout
    self.wait_for_pyo_page()
  File "/Users/sw1043146/nvidia-bot2/stores/amazon.py", line 147, in wait_for_pyo_page
    selenium_utils.wait_for_any_title(self.driver, CHECKOUT_TITLES + SIGN_IN_TITLES)
  File "/Users/sw1043146/nvidia-bot2/utils/selenium_utils.py", line 92, in wait_for_any_title
    WebDriverWait(d, time).until(AnyEc(*my_args_list))
  File "/Users/sw1043146/.local/share/virtualenvs/nvidia-bot2-ZF3XGFqN/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by Opt147** [comment]
is there a fix or???

**Comment by DakkJaniels** [comment]
or??? I think this should be fixed under the latest version.

**Comment by Opt147** [comment]
have you tried it out?

**Comment by DakkJaniels** [comment]
I have Amazon Prime, so I don't see the page.

**Comment by Opt147** [comment]
i just got the 1.99 trial but after ill test it out and hopefully it works
