### ISSUE TITLE
Error on Checkout

### ISSUE THREAD

**Issue by jfeliciano-dev** [Hari-Nagarajan/fairgame#269]
Pretty heartbroken, thought it had it but it bugged out somehow.  Was not near the machine so I really have no clue what happened.![image](https://user-images.githubusercontent.com/56049071/97785867-1067cf00-1b7e-11eb-9da7-f8d733c819b0.jpeg)

**Comment by DakkJaniels** [comment]
It would be helpful if you could post the screenshot, per the error message, if one exists.

**Comment by jfeliciano-dev** [comment]
Yeah I was on mobile my bad.  Here's the picture. I'm assuming it sold out instant which is fine but breaking caused it to miss another drop.

![amazon-wait_for_pages](https://user-images.githubusercontent.com/56049071/97789373-4a44cf80-1b96-11eb-86a7-d8dc565a0c2b.png)

**Comment by worst-mod-confirmed** [comment]
Appears the item sold out before the click flow had a chance to complete. Keep trying.

**Comment by unapproachable** [comment]
Similar issue here with a timeout exception from Selenium.  It seems we need a try: finally wrapper of some sort.  It failed to take a screenshot in my case because the failure occurred in the snapshot code:

> 2020-11-21 01:02:56 COMPUTER nvidia-bot[5544] INFO Item in stock and under reserve!
2020-11-21 01:02:59 COMPUTER nvidia-bot[5544] INFO clicking add to cart
2020-11-21 01:02:59 COMPUTER nvidia-bot[5544] INFO attempting to buy B08LF32LJ6
2020-11-21 01:02:59 COMPUTER nvidia-bot[5544] INFO Waiting for Cart Page
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "G:\Projects\nvidia-bot\cli\cli.py", line 27, in decorator
    func(*args, **kwargs)
  File "G:\Projects\nvidia-bot\cli\cli.py", line 81, in amazon
    amzn_obj.run_item(test=test)
  File "G:\Projects\nvidia-bot\stores\amazon.py", line 215, in run_item
    if self.checkout(test=test):
  File "G:\Projects\nvidia-bot\stores\amazon.py", line 520, in checkout
    self.driver.save_screenshot("screenshot.png")
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\.virtualenvs\nvidia-bot-I_A8HX3N\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=87.0.4280.66)

**Comment by worst-mod-confirmed** [comment]
This situation is better handled with the new checkout flow.

**Comment by houcem85** [comment]
![image](https://user-images.githubusercontent.com/57689434/120315919-78140300-c2a2-11eb-89d7-13a3bcfd0010.jpeg)

"Timed out taking screenshot" what does it mean ?

**Comment by houcem85** [comment]
![image](https://user-images.githubusercontent.com/57689434/120318387-68e28480-c2a5-11eb-9707-03c7a621fd7a.jpeg)

Place order clicked but then error taking screenshot
