### ISSUE TITLE
Failed checkout, and exception thrown trying to screenshot

### ISSUE THREAD

**Issue by bulletbeall** [Hari-Nagarajan/fairgame#383]
Problem is exactly as described in the title.
Upon successful add to card, it cant find the checkout button. This becomes impossible to debug because it then fails to screenshot?

2020-12-02 14:09:01 DESKTOP-B nvidia-bot[7264] INFO Waiting for home page.
2020-12-02 14:09:01 DESKTOP-B nvidia-bot[7264] INFO Already logged in
2020-12-03 16:13:37 DESKTOP-B nvidia-bot[7264] INFO Item in stock and under reserve!
2020-12-03 16:13:37 DESKTOP-B nvidia-bot[7264] INFO clicking add to cart
2020-12-03 16:13:41 DESKTOP-B nvidia-bot[7264] INFO clicking checkout.
2020-12-03 16:13:41 DESKTOP-B nvidia-bot[7264] ERROR couldn't find buttons to proceed to checkout
Traceback (most recent call last):
  File "C:\myArea\Documents\GitHub\nvidia-bot\stores\amazon.py", line 516, in handle_cart
    self.driver.find_element_by_xpath('//*[@id="hlb-ptc-btn-native"]').click()
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="hlb-ptc-btn-native"]"}
  (Session info: chrome=87.0.4280.66)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\myArea\Documents\GitHub\nvidia-bot\stores\amazon.py", line 519, in handle_cart
    self.driver.find_element_by_xpath('//*[@id="hlb-ptc-btn"]').click()
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="hlb-ptc-btn"]"}
  (Session info: chrome=87.0.4280.66)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\app.py", line 5, in <module>
    cli.main()
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\myArea\Documents\GitHub\nvidia-bot\cli\cli.py", line 30, in decorator
    func(*args, **kwargs)
  File "C:\myArea\Documents\GitHub\nvidia-bot\cli\cli.py", line 126, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "C:\myArea\Documents\GitHub\nvidia-bot\stores\amazon.py", line 260, in run
    self.navigate_pages(test)
    value = func(*args, **kwargs)
  File "C:\myArea\Documents\GitHub\nvidia-bot\stores\amazon.py", line 443, in navigate_pages
    self.handle_cart()
  File "C:\myArea\Documents\GitHub\nvidia-bot\utils\debugger.py", line 15, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\myArea\Documents\GitHub\nvidia-bot\stores\amazon.py", line 523, in handle_cart
    self.save_screenshot("ptc-error")
  File "C:\myArea\Documents\GitHub\nvidia-bot\stores\amazon.py", line 631, in save_screenshot
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\myArea\.virtualenvs\nvidia-bot-DLJ32YuF\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=87.0.4280.66)

**Comment by worst-mod-confirmed** [comment]
Update to the latest.
