### ISSUE TITLE
Crash on order placed screenshot/timeout

### ISSUE THREAD

**Issue by GoodRevrnd** [Hari-Nagarajan/fairgame#386]
See below.  Makes it all the way to order placed but crashes on screenshot timeout.  I thought I had read this was a bug that was fixed but I'm updated, unsure if related.

```
2020-12-04 04:28:09 Beep nvidia-bot[19064] INFO Item in stock and under reserve!
2020-12-04 04:28:10 Beep nvidia-bot[19064] INFO clicking add to cart
2020-12-04 04:28:10 Beep nvidia-bot[19064] INFO attempting to buy B07M63H81H
2020-12-04 04:28:10 Beep nvidia-bot[19064] INFO Waiting for Cart Page
2020-12-04 04:28:10 Beep nvidia-bot[19064] INFO Quick redirect to checkout page
2020-12-04 04:28:10 Beep nvidia-bot[19064] INFO clicking checkout.
2020-12-04 04:28:10 Beep nvidia-bot[19064] INFO Waiting for Place Your Order Page
2020-12-04 04:28:41 Beep nvidia-bot[19064] INFO Attempting to Finish checkout
2020-12-04 04:28:41 Beep nvidia-bot[19064] INFO Clicking Button: Proceed to checkout (1 item)
2020-12-04 04:28:41 Beep nvidia-bot[19064] INFO Waiting for Order completed page.
2020-12-04 04:29:11 Beep nvidia-bot[19064] INFO Order Placed.
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Beep\Documents\GitHub\nvidia-bot\cli\cli.py", line 27, in decorator
    func(*args, **kwargs)
  File "C:\Users\Beep\Documents\GitHub\nvidia-bot\cli\cli.py", line 109, in amazon
    amzn_obj.run_item(delay=delay, test=test)
  File "C:\Users\Beep\Documents\GitHub\nvidia-bot\stores\amazon.py", line 249, in run_item
    if self.checkout(test=test):
  File "C:\Users\Beep\Documents\GitHub\nvidia-bot\stores\amazon.py", line 514, in checkout
    self.save_screenshot("order-placed")
  File "C:\Users\Beep\Documents\GitHub\nvidia-bot\stores\amazon.py", line 322, in save_screenshot
    if self.driver.save_screenshot(file_name):
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Beep\.virtualenvs\nvidia-bot-jrIn3ToZ\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=87.0.4280.66)
```

**Comment by worst-mod-confirmed** [comment]
Update to the latest.
