### ISSUE TITLE
Element not clickable

### ISSUE THREAD

**Issue by Jamiex64** [Hari-Nagarajan/fairgame#405]
File "C:\Users\Jamie\Documents\GitHub\fairgame\stores\amazon.py", line 347, in login
    self.driver.find_element_by_xpath('//*[@id="ap_email"]').send_keys(
  File "C:\Users\Jamie\.virtualenvs\fairgame-0T3_mkvn\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\Jamie\.virtualenvs\fairgame-0T3_mkvn\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Jamie\.virtualenvs\fairgame-0T3_mkvn\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jamie\.virtualenvs\fairgame-0T3_mkvn\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=87.0.4280.88)

This is the output from the console after its found the item, added it to the cart, asked for my email and then on the password that is the error.

**Comment by DakkJaniels** [comment]
Fixed under 0.5.3.

**Comment by gannonprudhomme** [comment]
I'm getting the same error after running `python app.py amazon` after entering credentials

```
$ python app.py amazon
2021-01-14 12:22:14 Username-Desktop fairgame[5828] INFO No Apprise config found at config/apprise.conf.
2021-01-14 12:22:14 Username-Desktop fairgame[5828] INFO For notifications, see config/apprise.conf_template
2021-01-14 12:22:14 Username-Desktop fairgame[5828] INFO FairGame v0.5.4
2021-01-14 12:22:14 Username-Desktop fairgame[5828] INFO Reading credentials from: config/amazon_credentials.json
Credential file password: ******
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO ==================================================
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO Starting Amazon ASIN Hunt for 2 Products with:
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO --Delay of 3.0 seconds
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO --Free Shipping items only
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO --Looking for 2 ASINs between 500.00 and 600.00
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO --Looking for 2 ASINs between 500.00 and 600.00
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO ==================================================
2021-01-14 12:22:21 Username-Desktop fairgame[5828] INFO Waiting for home page.
2021-01-14 12:22:22 Username-Desktop fairgame[5828] INFO Lets log in.
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Username\Documents\workspace\fairgame\cli\cli.py", line 41, in decorator
    func(*args, **kwargs)
  File "C:\Users\Username\Documents\workspace\fairgame\cli\cli.py", line 189, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "C:\Users\Username\Documents\workspace\fairgame\stores\amazon.py", line 324, in run
    self.handle_startup()
  File "C:\Users\Username\Documents\workspace\fairgame\utils\debugger.py", line 15, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\Username\Documents\workspace\fairgame\stores\amazon.py", line 408, in handle_startup
    self.driver.find_element_by_xpath(xpath).click()
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Username\.virtualenvs\fairgame-qAX0y_Yj\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable: element has zero size
  (Session info: chrome=87.0.4280.88)
```

config:
```json
{
  "asin_groups": 2,
  "asin_list_1": ["B08164VTWH", "B0837SM1SW"],
  "reserve_min_1": 500,
  "reserve_max_1": 600,
  "asin_list_2": ["B08164VTWH", "B0837SM1SW"],
  "reserve_min_2": 500,
  "reserve_max_2": 600,
  "amazon_website": "smile.amazon.com"
}
```

Python version: 3.8.7

I'm going to try to re-install everything and retry with the same configuration.

**Comment by gannonprudhomme** [comment]
Re-installing everything seemed to fix it, but will comment again if the issue continues to occur.
