### ISSUE TITLE
Bot is indicating order has been placed - but it's not actually completing the process

### ISSUE THREAD

**Issue by ShinobiAlchemist** [Hari-Nagarajan/fairgame#421]
(nvidia-bot-xEfco32c) D:\Library\Documents\GitHub\nvidia-bot>python app.py amazon
2020-12-12 10:55:02 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Initializing Apprise handler
2020-12-12 10:55:02 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Initializing other notification handlers
2020-12-12 10:55:02 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Enabled Handlers: ['Audio']
2020-12-12 10:55:07 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Waiting for home page.
2020-12-12 10:55:08 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Already logged in
2020-12-12 10:55:09 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Checking stock for items.
2020-12-12 14:44:32 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Item in stock and under reserve!
2020-12-12 14:44:38 DESKTOP-GRTPVIN nvidia-bot[8040] INFO clicking add to cart
2020-12-12 14:44:38 DESKTOP-GRTPVIN nvidia-bot[8040] INFO attempting to buy B08164VTWH
2020-12-12 14:44:38 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Waiting for Cart Page
2020-12-12 14:44:38 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Quick redirect to checkout page
2020-12-12 14:44:38 DESKTOP-GRTPVIN nvidia-bot[8040] INFO clicking checkout.
2020-12-12 14:44:38 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Waiting for Place Your Order Page
2020-12-12 14:45:08 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Attempting to Finish checkout
2020-12-12 14:45:08 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Clicking Button: Proceed to checkout (1 item)
2020-12-12 14:45:08 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Waiting for Order completed page.
2020-12-12 14:45:38 DESKTOP-GRTPVIN nvidia-bot[8040] INFO Order Placed.
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Library\Documents\GitHub\nvidia-bot\cli\cli.py", line 27, in decorator
    func(*args, **kwargs)
  File "D:\Library\Documents\GitHub\nvidia-bot\cli\cli.py", line 109, in amazon
    amzn_obj.run_item(delay=delay, test=test)
  File "D:\Library\Documents\GitHub\nvidia-bot\stores\amazon.py", line 249, in run_item
    if self.checkout(test=test):
  File "D:\Library\Documents\GitHub\nvidia-bot\stores\amazon.py", line 514, in checkout
    self.save_screenshot("order-placed")
  File "D:\Library\Documents\GitHub\nvidia-bot\stores\amazon.py", line 322, in save_screenshot
    if self.driver.save_screenshot(file_name):
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\[Username]\.virtualenvs\nvidia-bot-xEfco32c\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=87.0.4280.88)

**Comment by DakkJaniels** [comment]
Update your code

**Comment by ShinobiAlchemist** [comment]
Vague much?
