### ISSUE TITLE
Crash on adding to cart

### ISSUE THREAD

**Issue by numbfx** [Hari-Nagarajan/fairgame#497]
Hi, I was using the bot and when it tried to make a purchase it got this error. Not sure what is wrong.
```
2021-02-09 09:13:18|0.6.0.dev5|INFO|Item in stock and in reserve range!
2021-02-09 09:13:18|0.6.0.dev5|INFO|clicking add to cart
Traceback (most recent call last):

Traceback (most recent call last):
  File "app.py", line 55, in <module>
    cli.main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/numbfx/fairgame/cli/cli.py", line 71, in decorator
    func(*args, **kwargs)
  File "/home/numbfx/fairgame/cli/cli.py", line 253, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "/home/numbfx/fairgame/stores/amazon.py", line 243, in run
    asin = self.run_asins(delay)
  File "/home/numbfx/fairgame/utils/debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "/home/numbfx/fairgame/stores/amazon.py", line 449, in run_asins
    if self.check_stock(asin, self.reserve_min[i], self.reserve_max[i]):
  File "/home/numbfx/fairgame/utils/debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "/home/numbfx/fairgame/stores/amazon.py", line 755, in check_stock
    condition: WebElement = atc_button.find_elements_by_xpath(
  File "/home/numbfx/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 381, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/home/numbfx/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 684, in find_elements
    return self._execute(Command.FIND_CHILD_ELEMENTS,
  File "/home/numbfx/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/numbfx/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/numbfx/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=89.0.4389.40)
```

**Comment by numbfx** [comment]
Realized this same same issues as #487
