### ISSUE TITLE
Fairgame crashed at 4am, item wasn't in stock

### ISSUE THREAD

**Issue by Mattiabe98** [Hari-Nagarajan/fairgame#500]
**Describe the bug**
I updated to the last commit yesterday night and today at 4am Fairgame crashed for no apparent reason, I don't think the item was in stock or Fairgame was trying to add it to cart. I will attach some logs, I don't have much else.

**To Reproduce**
1. Get latest dev commit
2. Run for some time
3. Crash?

**Expected behavior**
I expected Fairgame to keep on running with no problems since nothing new had happened.

**Screenshots**
There are sadly no screenshots related to the time of the crash.

**Desktop (please complete the following information):**
Windows 10, latest patch, Python 3.8.7

**Additional context**

```
2021-02-11 04:29:56|0.6.0.dev5|INFO|No offers found.  Moving on.
Traceback (most recent call last):
  File "C:\Users\Mattia\Desktop\fairgame-es\app.py", line 55, in <module>
    cli.main()
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Mattia\Desktop\fairgame-es\cli\cli.py", line 71, in decorator
    func(*args, **kwargs)
  File "C:\Users\Mattia\Desktop\fairgame-es\cli\cli.py", line 253, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "C:\Users\Mattia\Desktop\fairgame-es\stores\amazon.py", line 243, in run
    asin = self.run_asins(delay)
  File "C:\Users\Mattia\Desktop\fairgame-es\utils\debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\Mattia\Desktop\fairgame-es\stores\amazon.py", line 427, in run_asins
    if self.check_stock(asin, self.reserve_min[i], self.reserve_max[i]):
  File "C:\Users\Mattia\Desktop\fairgame-es\utils\debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\Mattia\Desktop\fairgame-es\stores\amazon.py", line 575, in check_stock
    open_offers_link.click()
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Mattia\.virtualenvs\fairgame-es-cZvcL4Ba\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=88.0.4324.150)

2021-02-11 04:30:04|0.6.0.dev5|INFO|Cleaning up after web driver...
```

From fairgame.log:
```
2021-02-10 20:37:41,551|0.6.0.dev5|DEBUG|Using proactor: IocpProactor
2021-02-10 20:37:41,691|0.6.0.dev5|WARNING|FairGame PRE-RELEASE v0.6.0.dev5
2021-02-10 20:37:41,691|0.6.0.dev5|INFO|Initializing Global configuration...
2021-02-10 20:37:41,707|0.6.0.dev5|INFO|Initializing Apprise handler using: config/apprise.conf
2021-02-10 20:37:41,707|0.6.0.dev5|DEBUG|Loading configuration: config/apprise.conf
2021-02-10 20:37:41,707|0.6.0.dev5|DEBUG|Loaded URL: tgram://xxxxx
2021-02-10 20:37:41,707|0.6.0.dev5|INFO|Loaded 1 entries from file://C%3A%5CUsers%5CMattia%5CDesktop%5Cfairgame-es%5Cconfig%5Capprise.conf?encoding=utf-8&cache=yes
2021-02-10 20:37:41,723|0.6.0.dev5|INFO|Found Telegram configuration
2021-02-10 20:37:41,723|0.6.0.dev5|INFO|Initializing Amazon configuration...
2021-02-10 20:37:41,723|0.6.0.dev5|INFO|Reading credentials from: config/amazon_credentials.json
2021-02-10 20:37:49,571|0.6.0.dev5|INFO|==================================================
2021-02-10 20:37:49,585|0.6.0.dev5|INFO|Starting Amazon ASIN Hunt on https://amazon.es/ for 3 Products with:
2021-02-10 20:37:49,637|0.6.0.dev5|INFO|--Offer URL of: https://amazon.es/dp/
2021-02-10 20:37:49,639|0.6.0.dev5|INFO|--Delay of 3.0 seconds
2021-02-10 20:37:49,646|0.6.0.dev5|INFO|--Shipping costs are included in price calculations
2021-02-10 20:37:49,667|0.6.0.dev5|INFO|--Looking for 1 ASINs between 280.00 and 320.00
2021-02-10 20:37:49,688|0.6.0.dev5|INFO|--Looking for 1 ASINs between 370.00 and 410.00
2021-02-10 20:37:49,693|0.6.0.dev5|INFO|--Looking for 1 ASINs between 400.00 and 510.00
2021-02-10 20:37:49,702|0.6.0.dev5|INFO|--No images will be requested
2021-02-10 20:37:49,703|0.6.0.dev5|INFO|==================================================
...
crash happens at 04:29:56
..
2021-02-11 04:29:50,224|0.6.0.dev5|DEBUG|Calling check_stock(<stores.amazon.Amazon object at 0x000002879A156F40>, 'B08164VTWH', 400.0, 510.0)
2021-02-11 04:29:50,802|0.6.0.dev5|DEBUG|Initial page title 
2021-02-11 04:29:51,091|0.6.0.dev5|DEBUG|        page url: https://www.amazon.es/dp/B08164VTWH/#aod
2021-02-11 04:29:54,815|0.6.0.dev5|DEBUG|After footer page title AMD Ryzen 9 5900X Box: Amazon.es: Informática
2021-02-11 04:29:55,972|0.6.0.dev5|DEBUG|             page url: https://www.amazon.es/dp/B08164VTWH/#aod
2021-02-11 04:29:56,110|0.6.0.dev5|INFO|No offers found.  Moving on.
2021-02-11 04:29:56,116|0.6.0.dev5|DEBUG|'check_stock' returned False
2021-02-11 04:29:59,117|0.6.0.dev5|DEBUG|Calling check_stock(<stores.amazon.Amazon object at 0x000002879A156F40>, 'B08166SLDF', 280.0, 320.0)
2021-02-11 04:29:59,118|0.6.0.dev5|DEBUG|Failed reconnect attempt. Pipe Not Found - Is Discord Running?
2021-02-11 04:29:59,461|0.6.0.dev5|DEBUG|Initial page title 
2021-02-11 04:29:59,465|0.6.0.dev5|DEBUG|        page url: https://www.amazon.es/dp/B08166SLDF/#aod
2021-02-11 04:30:02,607|0.6.0.dev5|DEBUG|After footer page title AMD Ryzen 5 5600X Box: Amd: Amazon.es: Informática
2021-02-11 04:30:02,623|0.6.0.dev5|DEBUG|             page url: https://www.amazon.es/dp/B08166SLDF/#aod
2021-02-11 04:30:02,759|0.6.0.dev5|DEBUG|Attempting to click the open offers link...
2021-02-11 04:30:03,682|0.6.0.dev5|INFO|Notifying 1 service(s) asynchronously.
2021-02-11 04:30:03,683|0.6.0.dev5|DEBUG|Using proactor: IocpProactor
2021-02-11 04:30:03,744|0.6.0.dev5|DEBUG|Telegram POST URL: https://api.telegram.org/xxxxxx/sendMessage (cert_verify=True)
2021-02-11 04:30:03,744|0.6.0.dev5|DEBUG|Telegram Payload: {'parse_mode': 'HTML', 'text': 'FairGame has crashed.', 'chat_id': xxx}
2021-02-11 04:30:03,911|0.6.0.dev5|INFO|Sent Telegram notification.
2021-02-11 04:30:04,617|0.6.0.dev5|INFO|Cleaning up after web driver...
2021-02-11 04:30:04,638|0.6.0.dev5|DEBUG|Killing 1968...
2021-02-11 04:30:04,639|0.6.0.dev5|DEBUG|Killing 1600...
2021-02-11 04:30:04,640|0.6.0.dev5|DEBUG|Killing 12620...
2021-02-11 04:30:04,641|0.6.0.dev5|DEBUG|Killing 9552...
2021-02-11 04:30:04,645|0.6.0.dev5|DEBUG|Killing 11476...
2021-02-11 04:30:04,649|0.6.0.dev5|DEBUG|Killing 9112...
2021-02-11 04:30:04,649|0.6.0.dev5|DEBUG|9112 not found. Continuing...
2021-02-11 04:30:04,649|0.6.0.dev5|DEBUG|Killing 11860...
2021-02-11 04:30:04,650|0.6.0.dev5|DEBUG|11860 not found. Continuing...
2021-02-11 04:30:04,651|0.6.0.dev5|DEBUG|Killing 6712...

```

**Comment by Crabo-7498** [comment]
Im pretty sure this is just an issue of RAM, try restarting the bot right before you sleep

**Comment by Mattiabe98** [comment]
> 
> 
> Im pretty sure this is just an issue of RAM, try restarting the bot right before you sleep

I don't think so, I never had this happen before updating. But I updated again to the latest commit and so far so good, the hotfix probably helped? Looks like Amazon added some button.
