### ISSUE TITLE
pipenv install fails on "Locking [packages] dependencies" on raspberry pi 4

### ISSUE THREAD

**Issue by marcolvz** [Hari-Nagarajan/fairgame#527]
**Describe the bug**
I followed [this](https://docs.google.com/document/d/1VUxXhATZ8sZOJxdh3AIY6OGqwLRmrAcPikKZAwphIE8/edit) guide and I fail every time I try to run pipenv install. I don't know why it seems to be looking for python 3.6 in the tracebacks but the default rn is 3.8.6

![image](https://user-images.githubusercontent.com/39943324/109353786-22802280-787d-11eb-9d16-5cefac840dc9.png)

 - OS: Raspberry Pi OS

**Comment by marcolvz** [comment]
### This is the full error:

(fairgame) pi@raspberrypi:~/fairgame $ pipenv install
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
Could not find a version of pywin32; sys_platform == 'win32' that matches your environment, it will be skipped.
pyobjc; sys_platform == 'darwin' doesn't match your environment, its dependencies won't be resolved.
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /home/pi/.local/share/virtualenvs/fairgame-3Td2oUte/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-on5xmud1/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-on5xmud1/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-on5xmud1/lxml/pip-egg-info
     cwd: /tmp/pip-resolver-on5xmud1/lxml/
Complete output (3 lines):
Building lxml version 4.6.2.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.
\----------------------------------------
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/build/metadata_legacy.py", line 115, in generate_metadata
    call_subprocess(
  File "/home/pi/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

(fairgame) pi@raspberrypi:~/fairgame $

**Comment by DakkJaniels** [comment]
show me `python --version`

**Comment by marcolvz** [comment]
> show me `python --version`

![image](https://user-images.githubusercontent.com/39943324/109356708-62490900-7881-11eb-8f92-2db5756b37e7.png)

**Comment by DakkJaniels** [comment]
Could try the instructions in the readme. Looks like some step was missed to associate the virtual environment with your 3.8 version

**Comment by marcolvz** [comment]
re-doing everything but following the guide in the readme proved to be a success, I did not try the bot just yet but it seemed to have been installed correctly so I will close this issue
