### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified when running amazon.bat for the first time

### ISSUE THREAD

**Issue by megalhaes** [Hari-Nagarajan/fairgame#591]
```
C:\Users\\Documents\GitHub\fairgame>cmd /k pipenv run python app.py amazon --test
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\cli\command.py", line 449, in run
    do_run(
  File "C:\Users\AppData\Roaming\Python\Python38\site-packages\pipenv\core.py", line 2547, in do_run
    run_fn(*run_args, **run_kwargs)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\core.py", line 2468, in do_run_nt
    p = _launch_windows_subprocess(script)
  File "C:\Users\\AppData\Roaming\Python\Python38\site-packages\pipenv\core.py", line 2458, in _launch_windows_subprocess
    return subprocess.Popen([command] + script.args, **options)
  File "c:\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\\Documents\GitHub\fairgame>
```

Hello, when running the amazon.bat for the first time this error occurs. I've tried reinstalling python and using different version but the problem persists. A Google search turned out to be unfruitful, maybe because I'm not the most literate of python users. Does anyone know of a possible solution? Thank you.

**Comment by DakkJaniels** [comment]
What was the output of running `INSTALL (RUN FIRST).bat`? Please run again and screenshot the output for both parts.

**Comment by megalhaes** [comment]
I'm unable to replicate the initial output and my attempts at removing the first installation were unsuccessful, here's the current output:

https://pasteboard.co/JTwpBDG.png

**Comment by DakkJaniels** [comment]
What about the pipenv part?

**Comment by megalhaes** [comment]
Here's the current output:

https://pasteboard.co/JTwyhsX.png

**Comment by megalhaes** [comment]
https://pasteboard.co/JTxTIPM.png

I apologize for the double post, I made a new installation attempt, this time on different directory, here's a more thorough output from the commands 

```
pip install pipenv
pipenv shell 
pipenv install
```

**Comment by megalhaes** [comment]
> 
> 
> What was the output of running `INSTALL (RUN FIRST).bat`? Please run again and screenshot the output for both parts.

Using the wiki I was able to at least partially uninstall the first instalation, these are the outputs: 

https://pasteboard.co/JTDJLPF.png

Unfortunately when opening the `amazon.bat` file I'm still getting the same error message.

**Comment by megalhaes** [comment]
Ok, figure this out. The problem was with the virtualenv directory path - my username consisted of two words with a space between them and although I did remove the space for both the python installation and the github repository the virtualenv directory is automatically created in the default appdata folder. Changed its path and the problem is corrected.
