### ISSUE TITLE
bot crushes after credentials

### ISSUE THREAD

**Issue by spawnaga** [Hari-Nagarajan/fairgame#597]
When running the updated version: I put the credentials then I get the chromedriver to start then immediately crushes with the following error:

Traceback (most recent call last):
  File "app.py", line 67, in <module>
    cli.main()
  File "/home/USER/.local/share/virtualenvs/fairgame-IljCGUvp/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/USER/.local/share/virtualenvs/fairgame-IljCGUvp/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/USER/.local/share/virtualenvs/fairgame-IljCGUvp/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/USER/.local/share/virtualenvs/fairgame-IljCGUvp/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/USER/.local/share/virtualenvs/fairgame-IljCGUvp/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/USER/Projects/fairgame/cli/cli.py", line 65, in decorator
    func(*args, **kwargs)
  File "/home/USER/Projects/fairgame/cli/cli.py", line 254, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "/home/USER/Projects/fairgame/stores/amazon.py", line 225, in run
    cart_quantity = self.get_cart_count()
  File "/home/USER/Projects/fairgame/stores/amazon.py", line 1180, in get_cart_count
    element = self.get_amazon_element(key="CART")
  File "/home/USER/Projects/fairgame/stores/amazon.py", line 1168, in get_amazon_element
    join_xpaths(amazon_config["XPATHS"][key])
KeyError: 'XPATHS'

I believe the dictionary for (amazon_config["XPATHS"]) is not found when trying to run the code. Please advise.

Thank you,

**Comment by DakkJaniels** [comment]
You have to copy all the new files from new version. You didn't copy fairgame.conf
