### ISSUE TITLE
newest version on chrome 90 crashes frequently

### ISSUE THREAD

**Issue by Matthew-Nehse** [Hari-Nagarajan/fairgame#700]
2021-04-16 20:18:56|0.6.5|ERROR|Traceback (most recent call last):
  File "C:\Users\m\git\fairgame-master2\cli\cli.py", line 66, in decorator
    func(*args, **kwargs)
  File "C:\Users\m\git\fairgame-master2\cli\cli.py", line 257, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "C:\Users\m\git\fairgame-master2\stores\amazon.py", line 265, in run
    asin = self.run_asins(delay)
  File "C:\Users\m\git\fairgame-master2\utils\debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\m\git\fairgame-master2\stores\amazon.py", line 449, in run_asins
    if self.check_stock(asin, self.reserve_min[i], self.reserve_max[i]):
  File "C:\Users\m\git\fairgame-master2\utils\debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\m\git\fairgame-master2\stores\amazon.py", line 650, in check_stock
    atc_buttons = self.get_amazon_elements(key="ATC_BUY_BOX")
  File "C:\Users\m\git\fairgame-master2\stores\amazon.py", line 1135, in get_amazon_elements
    join_xpaths(amazon_config["XPATHS"][key])
KeyError: 'ATC_BUY_BOX'

I get the exact same error on windows, mac, and linux. On mac and linux it happens in less than hour. Windows crashes every 12 hours. The error is identical on all platforms. The item number is not the same on each crash.

**Comment by DakkJaniels** [comment]
It's crashing because you didn't actually actually update all the files when you updated to 0.6.5.
