### ISSUE TITLE
Error when checking out

### ISSUE THREAD

**Issue by polow** [Hari-Nagarajan/fairgame#842]
I have latest version installed and only checking one product, i get this Error :

`Found 6 offers for B08V1WK4LB.  Evaluating offers...
2021-11-19 15:23:56|0.6.9|INFO|Item B08V1WK4LB in stock and in reserve range: 1299.99 + 0.00 shipping <= 1300.0
2021-11-19 15:23:56|0.6.9|INFO|Adding to cart
2021-11-19 15:23:56|0.6.9|INFO|Attempting Add To Cart with offer ID...
2021-11-19 15:23:58|0.6.9|INFO|Clicking button
2021-11-19 15:23:58|0.6.9|INFO|Button clicked
2021-11-19 15:24:01|0.6.9|INFO|Looking for Proceed To Checkout button...
2021-11-19 15:24:02|0.6.9|ERROR|You have no items in cart. Going back to stock check.
2021-11-19 15:24:02|0.6.9|INFO|Checking ASIN: B08V1WK4LB.
2021-11-19 15:24:09|0.6.9|ERROR|Traceback (most recent call last):
  File "C:\Users\XXXX\Documents\GitHub\fairgame-master\fairgame-master\cli\cli.py", line 66, in decorator
    func(*args, **kwargs)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\cli\cli.py", line 257, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\stores\amazon.py", line 269, in run
    asin = self.run_asins(delay)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\utils\debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\stores\amazon.py", line 459, in run_asins
    if self.check_stock(asin, self.reserve_min[i], self.reserve_max[i]):
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\utils\debugger.py", line 34, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\stores\amazon.py", line 597, in check_stock
    WebDriverWait(
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\.venv\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\stores\amazon.py", line 600, in <lambda>
    lambda d: d.find_element_by_xpath(
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\XXX\Documents\GitHub\fairgame-master\fairgame-master\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=96.0.4664.45)

2021-11-19 15:24:09|0.6.9|INFO|Cleaning up after web driver...`

What's wrong with it?

**Comment by authrequest** [comment]
Looks like the cart was empty, this happens when you are able to add to cart but it doesn't actually add item to cart. Then it looks like the tab crashed. This caused the error.
