### ISSUE TITLE
don't know what is wrong

### ISSUE THREAD

**Issue by trothh** [Hari-Nagarajan/fairgame#862]
**Describe the bug**
2022-07-20 18:53:13,069|0.6.9|WARNING|--Testing Mode.  NO Purchases will be made.
2022-07-20 18:53:13,069|0.6.9|INFO|==================================================
2022-07-20 18:53:13,069|0.6.9|INFO|Waiting for home page.
2022-07-20 18:53:13,080|0.6.9|ERROR|Traceback (most recent call last):
  File "C:\Users\****\Documents\GitHub\fairgame\cli\cli.py", line 66, in decorator
    func(*args, **kwargs)
  File "C:\Users\****\Documents\GitHub\fairgame\cli\cli.py", line 257, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "C:\Users\****\Documents\GitHub\fairgame\stores\amazon.py", line 231, in run
    self.get_page(url=AMAZON_URLS["BASE_URL"])
  File "C:\Users\****\Documents\GitHub\fairgame\stores\amazon.py", line 1674, in get_page
    check_cart_element = self.driver.find_element_by_xpath(
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'

2022-07-20 18:53:13,080|0.6.9|INFO|Cleaning up after web driver...

**Comment by DakkJaniels** [comment]
find_element_by_xpath and find_element_by_id was removed from selenium. The code needs to be updated (by someone) to stop using it.

**Comment by cykaal** [comment]
Specify the version of selenium in pipfile e.g. 4.2.0 (must be previous to 4.3.0) solves this problem.

**Comment by johnsoe2** [comment]
I still get this exact error when running Selenium 4.2.0, Chromedriver_PY 102.0.5005.61, Chrome 102.0.5005.63, Python 3.8.15. Any idea what I might have missed?
